version: '3'

services:
  nginx:
    build:
      context: ./nginx
    environment:
      TELEGRAF_HOST: 172.16.238.10
      GRAFANA_HOST: "${GRAFANA_HOST}"
      GRAFANA_PORT: "${GRAFANA_PORT}"
      WEECHAT_HOST: "${WEECHAT_HOST}"
      WEECHAT_PORT: "${WEECHAT_PORT}"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${SSL_CERTIFICATE}:/etc/ssl/certs/server.crt:ro
      - ${SSL_CERTIFICATE_KEY}:/etc/ssl/private/server.key:ro
      - ${SSL_TRUSTED_CERTIFICATE}:/etc/ssl/private/ca-certs.pem:ro
      - ${DH_PARAMS}:/etc/ssl/certs/dhparam.pem:ro
    networks:
      - nginx-cluster-network
    logging:
      driver: syslog
      options:
        syslog-address: "${SYSLOG_ADDRESS}"
  telegraf:
    image: telegraf:1.2.1-alpine
    environment:
      HOSTNAME: "${AGENT_HOSTNAME}"
      AGENT_INTERVAL: "${AGENT_INTERVAL}"
      INFLUXDB_HOST: "${INFLUXDB_HOST}"
      INFLUXDB_PORT: "${INFLUXDB_PORT}"
      NGINX_STATUS_URL: http://nginx/nginx_status
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
    networks:
      nginx-cluster-network:
        ipv4_address: 172.16.238.10
    logging:
      driver: syslog
      options:
        syslog-address: "${SYSLOG_ADDRESS}"
    depends_on:
      - nginx

networks:
  nginx-cluster-network:
    ipam:
      config:
        - subnet: 172.16.238.0/24
